### ISSUE TITLE
[Bug] Background image is not found, instead one completly hidden on the page

### ISSUE THREAD

**Issue by Stimmenhotel** [StigNygaard/xIFr#11]
Just trying the add-on I found this website: https://www.nadinegrenningloh.de/businessbewerbungsfotos
If you try to get the exif info of the big background picture, you only receive another one that is not even presented on the page or page-info/ressources.

I don't need to have this picture/info about this picture, but since the add-on is not working on this site, i will just post this as a issue. Maybe this will help to improve the tool even further.

**Comment by StigNygaard** [comment]
I have also noticed that xIFr is in trouble on f.ex. 1x.com.
There will probably always be some amount of "guessing" in the way xIFr finds the "right" image in some cases. However I have already thought about a few optimizations which should do the guessing a bit better.
Maybe I should make some kind of meta or tracking bug where people can add examples of places where xIFr fails finding the right/expected photo. It could be a good source for testing new developments of the "Deep Search" functionality :-)

**Comment by Stimmenhotel** [comment]
The meta issue sounds good, so it won't clutter the issues page for every site it won't work.

**Comment by StigNygaard** [comment]
A lot of improvements have been made to "deep search" in xIFr over the last year. Maybe that have fixed issue, or maybe website has just changed. Very likely both :-)
Anyway, since latest xIFr v2.15.0 works fine with website, I'm closing this.
