### ISSUE TITLE
[Bug] Won't Work.

### ISSUE THREAD

**Issue by Am-I-bilingual-if-I-code** [StigNygaard/xIFr#18]
Made a GitHub account for this post. This extension doesn't work for me. On the starting guide website with pictures, the extension doesn't show any data, but another exif extension does. I've tried this extension on multiple websites, but it won't work. Oddly enough, the github README.md pictures does actually show data. (For the longest time, I thought it wouldn't work because of extension/browser incompatibility since I have _numerous_ extensions and modified security/privacy settings, but this gave me hope.) (My Firefox browser and the extension is up to date too.) I've had this extension for years [in hope that it will work one day] and it's always been this way to my knowledge [for me]. Here's a copy and pasted version of what I see(other than the code) when I try to run this extension (the work-around also doesn't work):
<html><body>
<div id="properties"><b><a href="https://www.rockland.dk/xIFr/img/LeMontSaintMichel-1000x562.jpg" id="filename" title="https://www.rockland.dk/xIFr/img/LeMontSaintMichel-1000x562.jpg">LeMontSaintMichel-1000x562.jpg</a></b>
      <span title="Content-type reported by server"><br>Content-type: <span id="contenttype"></span></span>
      <span title="Size reported by server"><br>Size: <span id="imgsize"></span> bytes (<span id="imgsize2">0.00 KB</span>)</span>
      <span title="Modified date reported by server"><br>Last modified: <span id="lastmodified"></span></span>
      <span><br>Dimensions: <span id="dimensions">1000x562 pixels</span></span>
      
    </div>
    <div id="messages" style="display: block;"><div><img src="moz-extension://9c1bc93e-0556-47c5-829a-71d3ef06969a/icons/error-7-32w.png" alt="!"> <i>Error trying to load image-file for parsing of the metadata!</i></div><div><img src="moz-extension://9c1bc93e-0556-47c5-829a-71d3ef06969a/icons/info-32w.png" alt="i"> <i>Possible
 work-around for error: Try opening image directly from above link, and 
open xIFr again directly from the displayed image</i></div><div><img src="moz-extension://9c1bc93e-0556-47c5-829a-71d3ef06969a/icons/info-32w.png" alt="i"> <i>No metadata found</i></div></div>
    

</body>
</html>[LeMontSaintMichel-1000x562.jpg](https://www.rockland.dk/xIFr/img/LeMontSaintMichel-1000x562.jpg)
Content-type:
Size: bytes (0.00 KB)
Last modified:
Dimensions: 1000x562 pixels
! Error trying to load image-file for parsing of the metadata!
i Possible work-around for error: Try opening image directly from above link, and open xIFr again directly from the displayed image
i No metadata found

**Comment by StigNygaard** [comment]
Hi @Am-I-bilingual-if-I-code 

I have no idea what's going on, and especially why it works on GitHub when not working (most) other places is confusing. But somewhere it is probably a conflict with one of your other extensions and/or your security settings.

Could try to having the browser console open (F12 -> "Console" tab) when using xIFr, and see if any errors are reported there when opening pictures on f.ex. the [introduction page](https://www.rockland.dk/xIFr/start/)?

Maybe it is also worth trying Firefox' "Troubleshoot Mode". It will temporarily disable extensions, themes, and custom settings in the browser. I don't know for sure if there is a way to re-enable only xIFr when in troubleshooting mode, but if you can re-enable xIFr and other extensions one-by-one maybe that could be good way to find a conflicting extension? (Firefox "Burger menu" -> "Help" -> "Troubleshoot Mode...").

Also you could install another version of Firefox _besides_ your current installation. For example you could try the [Firefox Developer Edition](https://www.mozilla.org/firefox/developer/). It will run independently of your current Firefox installation (separate profiles). So you could start with a clean browser installation (where xIFr hopefully will work) and make experiments with that to identify when it eventually stops working again.

Finally you could try the "backend fetch"-fix that worked as work-around for a uBO conflict another user had. See https://github.com/StigNygaard/xIFr/issues/17. But even if this quick fix works, I'm still very curious to see what problems you (probably) got reported in F12 browser console when using your current setup.

**Comment by Am-I-bilingual-if-I-code** [comment]
There is an error in the console tab:
"Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://9c1bc93e-0556-47c5-829a-71d3ef06969a/lib/mozilla/browser-polyfill.js
Source Map URL: browser-polyfill.js.map"

I need to get some sleep for now, but I will try the other recommendations tomorrow if you don't know what the problem is from this. (I'm guessing it has something to do with javascript because I see js and I have it blocked by default.) Thanks for the quick response!

**Comment by StigNygaard** [comment]
Good to hear there are progress identifying and solving issue.

The browser-polyfill.js error is interesting. I don't exactly understand the error or its cause. But that particular script file is part of xIFr internally. The script file should NOT be needed to run xIFr in a Firefox browser, but is included with xIFr to make it possible to run xIFr in Chrome browsers too (even though it isn't officially available for Chrome/Chromium browsers, xIFr can actually run with limited functionality). So a bit weird you get an error referring to that file. But it could also just be the way the error is caught, that makes it look like it is related browser-polyfill.js. Root cause could still be somewhere else.
But you are not by any chance faking your browser's useragent to make it look like a Chrome browser? Potentially also confusing xIFr or browser-polyfill?

**Comment by Am-I-bilingual-if-I-code** [comment]
#17 fixed everything. Also, yes I am faking my browser's useragent to make it look like a Chrome browser. Sorry for not responding sooner and not looking in the closed section. Thanks for all the help though.

**Comment by StigNygaard** [comment]
👍 Good we found a way to make it work.

**Comment by StigNygaard** [comment]
FYI @Am-I-bilingual-if-I-code  or anyone else who might have enabled "Force backend-fetch" in xIFr's "secret settings" (The "fix" mentioned in #17 ).
In the latest versions of xIFr I have changed the strategy in the default "Autoselect type of fetch". It might work in more cases than forcing xIFr to always do "backend-fetch". At least I suggest you try reverting to the autoselect-mode again.

I might do further adjustments to the strategy in autoselect-mode, based on feedback and my own experiences. But current strategy is doing a "frontend fetch" when image is embedded from _same_ domain as the webpage itself, or if image is embedded with a file:, blob:, or data: URL. In all other cases xIFr will now do a "backend fetch" in autoselect-mode.
