### ISSUE TITLE
Solved [Need Just click the Flickr Badge added to the preview (the 2Balls Blue and Red ) -  Using in v2.20.0 the  "Search for the originating photopage on Flickr "

### ISSUE THREAD

**Issue by decembre** [StigNygaard/xIFr#21]
Seems their is a problem about it.

I tested this image:
https://www.flickr.com/photos/56851584@N06/34835074474/in/faves-93624663@N00/
Found in theses favs:
https://www.flickr.com/photos/dominictalvola/favorites/page3/

When in these pages it try to find the original image,
the link proposal don't work:
https://flickr.com/e/HEDNuejBrN0F1AIi4OJY7lhf7iYjMopZnJHt8gEsQVk%3D

error message:
"This is not the page you're looking for."

Same problem with an example used in  <a href="https://www.flickr.com/groups/flickrhacks/discuss/72157721920375928/">Find the original poster of a link like https://live.staticflickr.com/XXXXXXXXX-z.jpg</a>:
https://farm3.static.flickr.com/2085/2177060015_258bcfaff9_m.jpg
Link proposal:
https://www.flickr.com/photos/e/yhu1uppujpzl6itkqapu9whjtowg0cgvvijwmlrlpx0=

**Comment by StigNygaard** [comment]
Hi @decembre 
I think I have tried all the examples you point to, and they all work fine for me.
You are sure you are seeing and clicking the "flickr badge" in xIFr?
Maybe you have some other extension interfering, or - maybe more likely - it was a temporary problem at Flickr?

**Comment by decembre** [comment]
I tested to disable PhotoShow which is new in my Quantum profile - ;-) 
Same pb...

Strange.
This link open the good page for you ?:
https://flickr.com/e/HEDNuejBrN0F1AIi4OJY7lhf7iYjMopZnJHt8gEsQVk%3D

**Comment by StigNygaard** [comment]
Ahh, @decembre . You clicked the "Notes" link! 😃 
Well, I have been wondering if it was intuitive enough, and maybe I should add a screenshot to explain.

But if you had more experience looking at Flickr images with xIFr, you had probably long time ago discovered that the "Notes" link is part of exif-data of the images, and is present for all display-version images on Flickr. It is in one of the more "exotic" exif-tags, and the link never works. I'm guessing it is some kind of identifier/reference used internally by Flickr.

**Comment by decembre** [comment]
Ok ;-)

Maybe you can just an add an external icon near the shot preview?
Or move the Origin link and its "Flickr Badge" in the right side (with a label like "Go to the originating page") ?
