### ISSUE TITLE
[feature] close window on Esc

### ISSUE THREAD

**Issue by atomGit** [StigNygaard/xIFr#8]
please consider allowing user to close the pop-up window on Esc key press

thanks for your work and privacy ethic :)

**Comment by StigNygaard** [comment]
Hi @atomGit 
Thanks for appreciating the privacy/etics policy. I spend quite a lot of time too finding out how to write it correct, precise and still short and simple to read :-)
Good idea with the ESC key shortcut to close window. I put it on my list...

**Comment by StigNygaard** [comment]
Hi @atomGit 
Latest version 2.1 adds some keyboard shortcuts, including Escape to close window.
Enjoy :-)

**Comment by atomGit** [comment]
thanks! much appreciated
